version: '3'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - BackEnd/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongo

graphql:
    image: mhart/alpine-node:8
    command: npm run dev
    restart: on-failure
    working_dir: /app
    volumes:
        - ./graphql:/app
        - ./models:/app/models
    ports:
        - "3002:3002"
    links: 
        - 'mongo'
    depends_on:
        - 'mongo'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db